# Generated by Django 5.1.4 on 2025-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_attempted_on_quizattempt_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default='option1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
