# Generated by Django 5.2 on 2025-04-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
    ]
